services:
  app:
    build: .
    container_name: my-app
    ports:
      - '${PORT}:3000'
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DATABASE}
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:13
    container_name: my-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
